from Moving_systems.Manipulator_class import Manipulator
from Moving_systems import Data_base

Manipulator.set_zero()
Manipulator.move_to_point(Motor_1_x_pick, Motor_1_y_pick, Motor_1_z_pick)
Manipulator.pick()
Manipulator.move_to_point(Motor_1_x, Motor_1_y, Motor_1_z)
Manipulator.setup()
Manipulator.move_to_point(Motor_2_x_pick, Motor_2_y_pick, Motor_2_z_pick)
Manipulator.pick()
Manipulator.move_to_point(Motor_2_x, Motor_2_y, Motor_2_z)
Manipulator.setup()
Manipulator.move_to_point(Motor_3_x_pick, Motor_3_y_pick, Motor_3_z_pick)
Manipulator.pick()
Manipulator.move_to_point(Motor_3_x, Motor_3_y, Motor_3_z)
Manipulator.setup()
Manipulator.move_to_point(Motor_4_x_pick, Motor_4_y_pick, Motor_4_z_pick)
Manipulator.pick()
Manipulator.move_to_point(Motor_4_x, Motor_4_y, Motor_4_z)
Manipulator.setup()
Manipulator.move_to_point(Electronic_module_x_pick, Electronic_module_y_pick, Electronic_module_z_pick)
Manipulator.pick()
Manipulator.move_to_point(Electronic_module_x, Electronic_module_y, Electronic_module_z)
Manipulator.setup()
Manipulator.move_to_point(Top_part_x_pick, Top_part_y_pick, Top_part_z_pick)
Manipulator.pick()
Manipulator.move_to_point(Top_part_x, Top_part_y, Top_part_z)
Manipulator.setup()
Manipulator.set_zero()


