from Moving_systems.Manipulator_class import Manipulator
from Moving_systems import Data_base

manipulator = Manipulator()
manipulator.set_zero()
manipulator.move_to_point(Motor_1_x_pick, Motor_1_y_pick)
manipulator.move_to_point(Motor_1_z_pick)
manipulator.pick()
manipulator.move_to_point(Motor_1_x, Motor_1_y)
manipulator.move_to_point(Motor_1_z)
manipulator.setup()
manipulator.move_to_point(Motor_2_x_pick, Motor_2_y_pick)
manipulator.move_to_point(Motor_2_z_pick)
manipulator.pick()
manipulator.move_to_point(Motor_2_x, Motor_2_y)
manipulator.move_to_point(Motor_2_z)
manipulator.setup()
manipulator.move_to_point(Motor_3_x_pick, Motor_3_y_pick)
manipulator.move_to_point(Motor_3_z_pick)
manipulator.pick()
manipulator.move_to_point(Motor_3_x, Motor_3_y)
manipulator.move_to_point(Motor_3_z)
manipulator.setup()
manipulator.move_to_point(Motor_4_x_pick, Motor_4_y_pick)
manipulator.move_to_point(Motor_4_z_pick)
manipulator.pick()
manipulator.move_to_point(Motor_4_x, Motor_4_y)
manipulator.move_to_point(Motor_4_z)
manipulator.setup()
manipulator.move_to_point(Electronic_module_x_pick, Electronic_module_y_pick)
manipulator.move_to_point(Electronic_module_z_pick)
manipulator.pick()
manipulator.move_to_point(Electronic_module_x, Electronic_module_y)
manipulator.move_to_point(Electronic_module_z)
manipulator.setup()
manipulator.move_to_point(Top_part_x_pick, Top_part_y_pick)
manipulator.move_to_point(Top_part_z_pick)
manipulator.pick()
manipulator.move_to_point(Top_part_x, Top_part_y)
manipulator.move_to_point(Top_part_z)
manipulator.setup()